# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=500)),
                ('creation_date', models.DateField()),
                ('publish_date', models.DateField()),
                ('category', models.CharField(choices=[('developer', 'Developer'), ('devops', 'DevOps'), ('automation', 'Developer')], max_length=10)),
            ],
        ),
    ]
